### ISSUE TITLE
Redeploy pipeline ingestion into `kube`-cluster

### ISSUE THREAD

**Issue by guzman-raphael** [vathes/ibl-navigator#120]
Daily DataJoint pipeline ingestion routine should be converted to appropriate `CronJob` so that it can be scheduled within the new cluster.

**Comment by iamamutt** [comment]
docker-compose file used for ingestion: https://github.com/datajoint-company/ibl-datajoint-utils/blob/main/ibl-pipeline-docker/docker-compose.yml

I can provide you with more details about the environment.

**Comment by Ernaldis** [comment]
This issue has been moved to the [ibl-gitops](https://github.com/datajoint-company/ibl-gitops/issues) repository.
